### ISSUE TITLE
Use of two firebase accounts

### ISSUE THREAD

**Issue by bpouzet** [myflashlab/Firebase-ANE#119]
Hi,

A have a question. Can we use two firebase accounts with the ANE? Like that https://firebase.googleblog.com/2016/12/working-with-multiple-firebase-projects-in-an-android-app.html

Thanks!

**Comment by myflashlab** [comment]
Hi @bpouzet , This feature is an advanced one and is used **very rarely** and because of that we decided not to include that in the ANE. *you are actually the first developer asking about this feature since last year when we released Firebase collection.* So, we hadn't have any plans for supporting that unless it's ordered as a custom order OR a lot of developers are requesting that.

**Comment by bpouzet** [comment]
Thank you for your answer.
