### ISSUE TITLE
Tracking ScreenViews on FirebaseAnalytics

### ISSUE THREAD

**Issue by tfnsyl** [myflashlab/Firebase-ANE#155]
## Environment ##
* Android API Version: 21
* iOS Version: 9
* AIR SDK Version: 27

## Problem Description ##

In Google Analytics, there is a trackScreenView that we can analyze which view in a game is being opened and how much time a user is spending on it. In Firebase Analytics, there seems to be such a feature described [here](https://firebase.google.com/docs/analytics/screenviews) 

I cant see a `setCurrentScreen` method in the ANE. Is there any plan on it, or any workaround for this version?

**Comment by myflashlab** [comment]
The thing is that AIR apps are running on only one ```UIViewController or Activity``` and considering that screen tracking on Firebase Analytics is highly dependent on Activities switching on Android and UIViewController switching on iOS, we can't have a similar thing on AIR apps.

Thanks for suggesting that, but because of how AIR works, it seems screentracking is not useful on AIR apps.
