### ISSUE TITLE
IOS auth crashes

### ISSUE THREAD

**Issue by 4malik** [myflashlab/Firebase-ANE#185]
Hi. Today i tried to use Firebase Auth on iOS.
Sign In by email and facebook works, 
But sign in by phone closes my app immediatly
Here my crash log from device:
[customer-2018-02-19-211757.zip](https://github.com/myflashlab/Firebase-ANE/files/1737694/customer-2018-02-19-211757.zip)
In output: FirebaseAuth(BaseClassFirebaseAuth) verifyPhoneNumber %my number here%

Also there is a crash after signOut:
[customer-2018-02-19-211704.zip](https://github.com/myflashlab/Firebase-ANE/files/1737695/customer-2018-02-19-211704.zip)

on output:
FirebaseAuth(BaseClassFirebaseAuth) onAuthStateChanged > _user is null now

after relauch I'm signed out.

Can you help? 
Device 7 Plus, iOS 11.2.5
AIR 27
used ANE LAB

ps. on android the same methods works perfect

**Comment by myflashlab** [comment]
The logs you sent does not show any useful information. You should keep the xcode log window open and as soon as the crash happens, copy the related part. That information is more useful. Try to be more specific.

**Comment by 4malik** [comment]
i showed you logs from phone. 
Im developing under windows. So what can i do to get some logs you need?

**Comment by 4malik** [comment]
Thats all sign out crash was of bad Firebase Database dispose.
So no more errors. Close issue.

ps. wish: add something from https://firebase.google.com/docs/auth/web/phone-auth about ios auth by phone

**Comment by myflashlab** [comment]
Glad that the problem is solved. Yet, [here](https://github.com/myflashlab/Firebase-ANE/wiki/D.4-Phone-Number#enable-phone-number-sign-in-for-your-firebase-project) we are saying:

> To sign in users by SMS, you must first enable the Phone Number sign-in method for your Firebase project:
 In the Firebase console, open the Authentication section.  
 On the Sign-in Method page, enable the Phone Number sign-in method.  
 On the iOS side, your app must be able to receive FCM. To do that, make sure you have installed the FCM ANE first.

What else do you think we should add?
