### ISSUE TITLE
Firebase Crash working on Android, but not on iOS

### ISSUE THREAD

**Issue by PippoApps** [myflashlab/Firebase-ANE#206]
Hi,
Crash logging and app crashing works perfectly on Adroid.

On iOS though, although other Firebase features work fine, Crash.crash() closes the app, but no crash report appears on Firebase console. I tried in several ways, AdHoc, testing, etc. always restarted the app after a crash, etc.

Since Firebase.sConnectedToGoogleApiClient is not available on iOS, how can I check wether API client is available on iOS?

Thank you
(your nightmare eheh)

**Comment by myflashlab** [comment]
> Crash.crash() closes the app,

This is the expected behavior. the app really crashes on iOS. And the crash report will be sent to Firebase only when the app runs again. Usually, these data reports get reflected on Firebase console with some delay. But eventually, they should work. Anyhow, We are building ```crashlytics``` ANE and it will replace the Crash ANE.

**Comment by PippoApps** [comment]
Yes, I know it's the expected behaviour. Problem is the ones from iOS (after a successful crash and restart) never appear on crash reports. Is there a way to verify that iOS is correctly connected to Firebase api? Is there a way to detect that on a restart Crash ANE is sending data to Firebase?
