### ISSUE TITLE
(DB) Transactions are running even when they should be "busy"

### ISSUE THREAD

**Issue by GV3** [myflashlab/Firebase-ANE#22]
Hi guys,

I have a scenario in which the user updates rapidly a counter. It's not different users it's the same user the one which updates his counter. 

So, I decided to use a transaction to ensure that the counter is always growing after I noticed that the order (or time) in which the setValue methods were called does not really represent when they  actually affect the data.

I noticed that when I called setValue() 30 times in one frame, updating the counter, the value of the last call was not necessarily the resulting value on the DB.

Anyways, I decided to use transactions for this, and although I follow the example code on the wiki, I still don't manage to understand a few things (missing also in the docs)

```
if (!refTransaction.runTransaction())
    {
        trace("transaction is currently busy, try again in a few seconds.");
        // setTimeout(onButtonClicked, 500, e);
    }
```

1 - The transactions are being called and processed EVEN when the `refTransaction.runTransaction()` returns `false`, is that correct? (I can breakpoint and follow the transaction and try to update the value, but the value only changes if `runTransaction()` returned `true`)

2 -  Why did you comment out   ` // setTimeout(onButtonClicked, 500, e);` in your exampe?

3 - Should I rather run the waiting transaction after the running transaction dispatches a `TRANSACTION_COMPLETE` or `TRANSACTION_FAILURE` event instead of using a timer?

4 - When should I use `e.mutableData.continueAbort();` ? This is really a mystery to me. I imagine that it should be used when I decide not to update the mutableData, but I could also just not call the `mutableData.setValue()` function.

5 - what for is the `setDelegate()` method? I could not find anything about it on the Firebase docu.

And last but not least...

6 -  In the docu you have 'repeats until the transaction is accepted or too many attempts have been made' I had an infinite amount of attempts for over two minute, the App couldn't react, but it never stopped. How many are "too many attempts" ? I will naturally not rely on it, and handle the possibility of too many running transactions in the code, but I'm just curious to know if such an emergency break exists, and if, when does it break.

Thanks in forward for your help 
:)

**Comment by myflashlab** [comment]
I agree that when working with Firebase Database, the transaction methods can look confusing at the beginning. But you will love how they work after you got more familiar with the process. Below, I will explain more about transactions and then I will answer your questions asked above.

Although described in details [here](https://github.com/myflashlab/Firebase-ANE/wiki/B.4-Save-Data#save-data-as-transactions) if I want to explain how transactions work in a simple term, I must say that using transactions are helpful when you have a node in your DB which you know it is very probable that it would be updated by many users at the same time. So, you run the transaction process and listen to the its progress event. The progress event will return the current state of your node value. This is where you must decide if you want to continue ```e.mutableData.continueSuccess();``` the transaction or abort it. ```e.mutableData.continueAbort();```

If you are aborting the progress, it means that you are not saving your value to the database. On the other hand, if you are continuing the transaction, it means that you are interested to update the **current** db value with the one you have just updated using the mutable data object. ```e.mutableData.setValue()```.

If you are making neither of the decisions, i.e ```continueSuccess()``` or ```continueAbort()```, your transaction WILL be corrupted! That's probably why you never understood what ```too many attempts``` means. So, you should ALWAYS make a decision at the end of the transaction progress callback function.

Now, let's answer your questions:
> The transactions are being called and processed EVEN when the refTransaction.runTransaction() returns false, is that correct?

No, if ```refTransaction.runTransaction()``` returns false, it means that no new transaction has started. This usually happens for a few milliseconds from when an older transaction had started before. And this will of course stop you from running new transactions too often. This will make sure that you are running only one active transaction in your app at a time. It's worthy to mention that if you are not making a final decision in your ```DBEvents.TRANSACTION_PROGRESS``` event, the old transaction would never stop and in result, ```runTransaction()``` will always return false.

> Why did you comment out // setTimeout(onButtonClicked, 500, e); in your exampe?

Simply because it's a sample. Maybe you wish to do other things in your app instead of using setTimeout. We also added the setTimeout sample to emphasize that a busy transaction can stay busy for a very short time.

> Should I rather run the waiting transaction after the running transaction dispatches a TRANSACTION_COMPLETE or TRANSACTION_FAILURE event instead of using a timer?

As explained above, you need to have a relook at this. I presume that by a waiting transaction, you mean a transaction that is dispatching ```DBEvents.TRANSACTION_PROGRESS```. If so, you should remember that you are the one who decides if the transaction should continue or be aborted. If you are continuing a transaction though, you should not expect that your data will be saved on the server. Why? because it is probable that another user has changed the live value few milliseconds before you while you where making a decision in your app. If that happens, the ```TRANSACTION_PROGRESS``` event will be called again and you need to make a new decision. This process can happen over and over again until it timeouts.

> When should I use e.mutableData.continueAbort(); ? This is really a mystery to me. I imagine that it should be used when I decide not to update the mutableData, but I could also just not call the mutableData.setValue() function.

I think you can answer this question yourself now based on what I explained above. However, I should add that when you call ```e.mutableData.setValue``` it does NOT mean that your value will be saved on the server! your value will be saved ONLY if you decide to continue the transaction by calling ```e.mutableData.continueSuccess();```

> what for is the setDelegate() method? I could not find anything about it on the Firebase docu.

Oops, our bad! You shouldn't had seen that method at all :) that is an ```internal``` method being used in the ANE. I just added the ```@private``` label to asdoc so it won't be seen in the doc anymore. Thanks for noticing.

> In the docu you have 'repeats until the transaction is accepted or too many attempts.......

I think this is well explained above.

If you need more explanation, do feel free to ask which part might still look confusing. We had a VERY hard time to sync all these processes on Android and iOS as how transactions work here in Adobe AIR is not similar to how the native sides work. We tried many other approaches to enable transactions for AIR but they were too complicated for end-users. I think you will get familiar with transactions in no time. We'd be glad to hear other devs feedback about their experience with transactions.

**Comment by myflashlab** [comment]
Will you update us if the problem is solved?

**Comment by GV3** [comment]
Of course guys!
I've been you dealing with other tasks in the meantime, I'll com back to this next week and will certainly update you.

Thanks for the long explanation!
👍

**Comment by GV3** [comment]
All is clear now and the App is working as it should. 

Thanks again for taking the time to clarify the transactions!
