### ISSUE TITLE
Multiple config files

### ISSUE THREAD

**Issue by tomjolly** [myflashlab/Firebase-ANE#229]
Due to our InfoSec policy we are looking into using multiple configs to allow us to seperate out our development testing from our live app. Is it possible to run the firebase FCM ane with a specified googleservices json/plist rather than the default one?

Cheers

**Comment by myflashlab** [comment]
I'm not sure I understand the question fully. the json/plist files are binded with your app package name and they are generated by your Firebase console.

**Comment by myflashlab** [comment]
aha, thanks for the explanation. unfortunately we were not able to get the manual initialization work in Firebase back in 2016, Firebase was very young then and maybe it had a bug that we couldn't make it work like how it was described in the docs. so we went on the default auto initialization and since then we've been living with that. *Almost all AIR devs using the ANE are needing only one instance*

Anyhow, I am marking this ticket so we can study it more on the next round of updates which we are working on right now. we'll update the ticket when we have more news on this.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
