### ISSUE TITLE
Need Help for Debugging

### ISSUE THREAD

**Issue by garymich** [myflashlab/Firebase-ANE#238]
## Environment ##
* Android API Version: 30
* iOS Version: NA
* AIR SDK Version: 30

## Problem Description ##
We have successfully created our ANELAB project and used it to add a number of ANEs to our Animate project. Out Main class extends MovieClip while most of your samples I have seen extend Sprite. I am wondering if there an issue with that.

Secondly I would like to debug the code in the Animate project. In order to debug I have to use the On Device Using USB option. I set a break point in my code and then deploy to my Android phone but the break point never gets hit. How can I debug this.

Any help you could provide would be greatly appreciated.

**Comment by myflashlab** [comment]
> Main class extends MovieClip while most of your samples I have seen extend Sprite. I am wondering if there an issue with that

It's fine. MovieClip is extended from a Sprite. In an AdobeAnimate project, you use MovieClips more often than Sprites and that's fine.

You should use the debug version as in the screenshot:
<img width="1127" alt="screen shot 2018-08-15 at 9 56 41 am" src="https://user-images.githubusercontent.com/1692948/44133636-cf9be01c-a071-11e8-94f4-a2c9bb74f8c0.png">

I'll be closing this issue because it is not related to ANEs. Please consider asking ANE related questions only.
