### ISSUE TITLE
Firebase core Ane

### ISSUE THREAD

**Issue by nikhilreddy123456** [myflashlab/Firebase-ANE#242]
Hi,

   There is no Core Ane in Analytics can you send the link to download Firebase core Ane

**Comment by myflashlab** [comment]
If you are a club member, you have access to all our ANEs. (Firebase Core ANE must be generated by you. We have placed an AIR desktop application in your membership downloaded zip package which you can install and generate the Core ANE This is explained in the "readme" file you have downloaded when purchasing the Core ANE.) If not, please note that all Firebase ANEs are dependent on the Core ANE. If you have purchased the Analytics ANE only, you can't run it because the Analytics is a child of the FirebaseCore like all the other ones. For detailed information about these relations, read here https://github.com/myflashlab/Firebase-ANE/wiki/A.3.-Add-the-SDK
