### ISSUE TITLE
Didn't see firebase Core

### ISSUE THREAD

**Issue by AmirSmarty** [myflashlab/Firebase-ANE#245]
I've checkout this product:  Firebase Air Native Extension (Analytics) Android+iOS - Silver × 1 , but I can't use it! Where is the firebase Core?

**Comment by myflashlab** [comment]
When purchasing the commercial version of FirebaseCore, there's an ```.air``` software in the zip file you download from your Myflashlabs panel. you need to install that software on your computer and follow the instruction there to be able to generate the FirebaseCore.ane file. 

The generated FirebaseCore.ane will have your Firebase server details embedded in it. That's why you are not seeing the .ane file at the beginning. you need to generate it yourself with your own configuration using the provided software.
