### ISSUE TITLE
Crashlytics doesn't compile for iOS on Windows machines

### ISSUE THREAD

**Issue by leossmith** [myflashlab/Firebase-ANE#251]
## Environment ##
* Windows Version: 10 64bit pro
* iOS Version: any
* AIR Version: any

## Problem Description ##
When compiling on Windows 10 and targeting iOS, while using Crashlytics, the following error occures:

Error occurred while packaging the application:

ld: in aot/stub/Crashlytics.framework/Crashlytics(CLSException.o), sectionForAddress(0xFFFFFE3D00002BF6) address not in any section for architecture arm64
Compilation failed while executing : ld64

## Steps to Reproduce ##
Compile a demo app with crashlytics in Windows 10

## Known Workarounds ##

**Comment by myflashlab** [comment]
ah, this again. it seems like the root of the problem is just like the one we have on the latest release of [Facebook ANE](https://github.com/myflashlab/facebook-ANE#requirements).

This will work fine if you build with a Mac but let's push Adobe to update the Windows SDK: https://tracker.adobe.com/#/view/AIR-4198557

Maybe we should open a new issue to make sure Adobe is paying attention to the different error messages. but considering that the source of all such errors are similar, I guess, if Adobe is just updating the windows side of their SDK, all similar problems would be fixed automatically, if not, we'll open new issues there.
