### ISSUE TITLE
(FCM) crash on start

### ISSUE THREAD

**Issue by artl82** [myflashlab/Firebase-ANE#40]
Hi!
On Android 5.0 and above application with fcm ane always crashes. I am using AIR SDK 23. Here is logcat from Asus Nexus 7 under Android 5.1.1.
[asus nexus7 crash log android 5.1.1.txt](https://github.com/myflashlab/Firebase-ANE/files/577425/asus.nexus7.crash.log.android.5.1.1.txt)

**Comment by myflashlab** [comment]
Well, from the logcat, I don't see anything that is directly related to the FCM ANE. Will you please test the ANE in your target devices again but this time make sure you are creating a test app with no extra codes in it? It seems like the source of the crash is something else rather than the FCM ANE.

**Comment by myflashlab** [comment]
Please let us know if you are still having a problem on this regard?

**Comment by myflashlab** [comment]
Please let us know if you are still having a problem on this regard?
