### ISSUE TITLE
(DB) All Children To Object? & Timestamp

### ISSUE THREAD

**Issue by User3001** [myflashlab/Firebase-ANE#52]
Hello,

I have two brief technical issues when using the Firebase ANE, any assistance would be greatly appreciated.

1. I am trying to pull all children from a database directory, and place them in children under an object. For example, let's say I have a few values under the USER_INFO branch such as ACCOUNT="ACTIVE", CURRENCY="EURO", etc.:

var ref:DBReference = mDatabase.child("users").child("USER_INFO");
var LOCAL_USER_INFO: Object = {};
 // Let's assume the event is dispatched and the variable "ref" has been updated to that location
LOCAL_USER_INFO = e.dataSnapshot.value;
trace (LOCAL_USER_INFO.CURRENCY);

When that trace command is supposed to return "EURO", it instead errors out. What can I do to achieve that desired result?

2. When I attempt to run "trace (DBServerValue.TIMESTAMP)" (as shown in demo AS files) the output returns "DBServerValue.TIMESTAMP", not the actual time.

How can I retrieve the server time as a Epoch timestamp? Such as: 1479002636

**Comment by myflashlab** [comment]
There are options for filtering and sorting data from the db, check [this](https://github.com/myflashlab/Firebase-ANE/wiki/B.5-Retrieve-Data#sorting-and-filtering-data) out.

About ```DBServerValue.TIMESTAMP```, you can use it to save the server time on the server side but you can't trace it out because that is a constant value on the client side and will be converted to a real value only on the server side. If you wish to see its value, you should read back the server value.
