### ISSUE TITLE
Where can I download and test FirebaseCore.ane?

### ISSUE THREAD

**Issue by martinrossil** [myflashlab/Firebase-ANE#7]
Hi guys!

Just amazing what you're creating! :)

I want to ask if it's possible to download and test Firebase before buying it?

regards Martin :)

**Comment by imalitavakoli** [comment]
Unfortunately the time for beta-testers is over to hand you the Beta version to test the ANEs...
But well, you can still back the [Kickstarter campaign](https://www.kickstarter.com/projects/1836143618/firebase-air-native-extension) and you not only receive the rewards for the pledge that you have picked but also will receive the Beta version of all the released Firebase ANEs immediately...

As we provide all of the campaign's backers with the early access to Beta version of the ANEs so that they can start using them in their apps' development workflow, until the campaign is over and they have full access to the final versions. Cheers :smile:

**Comment by martinrossil** [comment]
Hi imalitavakoli.

Thanx for your fast reply :)

I'll head over to the Kickstarter campaign and take a look.

Again, thanx for doing such an amazing job to help AIR developers use Firebase :)

regards Martin.

**Comment by martinrossil** [comment]
Hi again imalitavakoli.

You wrote that ALL backers will recieve the Beta ANEs right?

It's because that Im unemployed and can't afford the 50$ that Kickstarter has as a minimum for getting ANEs or am I missing something here?

Thanx :)

**Comment by imalitavakoli** [comment]
Yes, that's right. The minimum pledge for getting a copy of the Firebase ANEs is $50. This is unfortunately the lowest price for getting ALL of the ANEs!

**Comment by martinrossil** [comment]
Hi again imalitavakoli.

Will the Club Membership 149.99$ give me access to the Firebase ANEs right away if I purchase that?

Thanx :)

**Comment by imalitavakoli** [comment]
Yes for sure. The club package includes the Firebase ANEs too.
