### ISSUE TITLE
conflict with another ANE

### ISSUE THREAD

**Issue by babakasol** [myflashlab/Firebase-ANE#75]
Hi,
I am using firebase ANE for notification in my as3 flex project and also admob_all_in_one_161220.ane for ads, but when i build the project it throws me the android manifest error :- 

Error occurred while packaging the application:

aapt tool failed:Warning: AndroidManifest.xml already defines versionCode (in http://schemas.android.com/apk/res/android); using existing value in manifest.
Warning: AndroidManifest.xml already defines versionName (in http://schemas.android.com/apk/res/android); using existing value in manifest.
Warning: AndroidManifest.xml already defines minSdkVersion (in http://schemas.android.com/apk/res/android); using existing value in manifest.
Warning: AndroidManifest.xml already defines targetSdkVersion (in http://schemas.android.com/apk/res/android); using existing value in manifest.
C:\Users\babakasol\AppData\Local\Temp\a932cb71-1b12-4403-9ce4-8fbe025705e0\res\values\values.xml:6: error: Attribute "imageAspectRatioAdjust" has already been defined 

can you help me with resolving this error ? 

Thanks

**Comment by mrgoonie** [comment]
I think it related to those Google Service Dependencies ANE. 

Try to unzip the "admob_all_in_one_161220.ane" to see which JAR file could be conflicted with your Firebase Dependency ANEs, then remove the correlative Firebase Dependency ANEs to avoid the conflict.

**Comment by myflashlab** [comment]
Unfortunately we are not able to help you on these kind of conflicts because they are built with other ANE providers And we don't have the time nor resources to check them.

However, you can try our [Admob ANE](http://www.myflashlabs.com/product/firebase-admob-air-native-extension/) with our latest Firebase release and see if that solves your problem. If not, feel free to open a new issue and we'll try to be helpful as much as possible.
